-- by rajdeepsinh 92600584028

DECLARE 
	EID NUMBER(3);
	ENAME VARCHAR2(50);
	DEPTNO NUMBER(2);
	DEPTNAME VARCHAR2(30);
	GENDER VARCHAR2(10);
	AGE NUMBER(3);
	BASICSAL NUMBER(7,2);
BEGIN
	ENAME:='&ENAME';
	DEPTNO:=&DEPTNO;
	DEPTNAME :='&DEPTNAME ';
	GENDER :='&GENDER  ';
	AGE :=&AGE;
	BASICSAL :=&BASICSAL;

	INSERT INTO sample_emp VALUES (NULL,ENAME,DEPTNO,DEPTNAME,GENDER,AGE,BASICSAL);
END;
/