CREATE OR REPLACE TRIGGER trigger_4
BEFORE INSERT OR UPDATE ON emp
FOR EACH ROW
DECLARE
	ID NUMBER;
BEGIN
    IF :NEW.basicsal > 50000 THEN
	DBMS_OUTPUT.PUT_LINE('ERROR : ');
	DBMS_OUTPUT.PUT_LINE('ORA-000: SALARY CANNOT BE MORE THAN 50000.');
	
	DELETE FROM EMP WHERE EID=:NEW.eid;
    END IF;
END;
/